### PR TITLE
Part 5 : Submit Task

### PR DESCRIPTION
**Pull request by WendyWang1031**
王薇婷
http://52.89.39.93:8000/
http://52.89.39.93:8000/attraction/10
http://52.89.39.93:8000/booking

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your every page calls Booking API for current booking data but it's not necessary obviously.

**Comment by WendyWang1031** [comment]
I've fixed the issue.
Thank you for the feedback.

王薇婷
http://52.89.39.93:8000/
http://52.89.39.93:8000/attraction/10
http://52.89.39.93:8000/booking

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by WendyWang1031** [comment]
Thank you!

**Pull request merged**
