### PR TITLE
Guide Part2 : Submit Task

### PR DESCRIPTION
**Pull request by WendyWang1031**
Hi! This is a part2-task for submission.

王薇婷
http://52.89.39.93:8000/

Thank you!

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
- Your code will load the same page multiple times if we scroll down and up quickly.
- When we do any search, we should start from page=0.
未命名-4

**Comment by WendyWang1031** [comment]
Ok, thank you for your feedback. I'll make the necessary adjustments.

**Comment by WendyWang1031** [comment]
Hi! This is a part2-task for modified version.

王薇婷
http://52.89.39.93:8000/

Thank you!

**Review by cwpeng — CHANGES_REQUESTED** [review]
If we search 北, there should have 2 pages data.

**Comment by WendyWang1031** [comment]
Thank you for your feedback! I will continue to work on this issue.

**Comment by WendyWang1031** [comment]
Hi! This is a part2-task for 3rd modified version.

王薇婷
http://52.89.39.93:8000/

Thank you!

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by WendyWang1031** [comment]
Thank you~

**Pull request merged**
