### PR TITLE
fix FastApi() in line 3

### PR DESCRIPTION
**Pull request by WendyWang1031**
Hi , 老師晚上安安 ,  我是王薇婷 , 再麻煩彭彭老師檢閱，謝謝您

### CODE REVIEW

**Review by cwpeng — APPROVED** [review]
OK.

**Comment by cwpeng** [comment]
Merge pull request after approval.

**Comment by cwpeng** [comment]
You should merge pull request after approval.

**Comment by cwpeng** [comment]
You should merge pull request after approval.

**Comment by cwpeng** [comment]
You MUST merge pull request after approval.

**Comment by cwpeng** [comment]
Do you get what I say? If not, you should contact me for details.

**Comment by WendyWang1031** [comment]
抱歉，現在才看到訊息，老師不好意思

**Comment by WendyWang1031** [comment]
已merge pull request after approval.

**Pull request merged**
